/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ASplit: typeof import('@arco-design/web-vue')['Split']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATree: typeof import('@arco-design/web-vue')['Tree']
    ATypographyParagraph: typeof import('@arco-design/web-vue')['TypographyParagraph']
    Editor: typeof import('./src/components/Editor.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
